name: Sanggar Web Auto Deploy CI/CD

on:
  push:
    branches:
      - miomidev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            git config --global --add safe.directory /home/miomideveloper/sanggar-web
            cd /home/miomideveloper/sanggar-web
            git fetch --all
            git reset --hard origin/miomidev
            chmod +x deploy.sh
            ./deploy.sh